### ISSUE TITLE
Trying to retrieve setting with no value given: 'bridge_extend_floating_walls'

### ISSUE THREAD

**Issue by Funkton** [smartavionics/CuraEngine#10]
**Application Version**
cura-mb-master-20200306 and up to 20200328

**Platform**
MacOS

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
Using existing profiles which sliced in previous builds, select use bridge settings checkbox. 

**Actual Results**
Hangs and never completes slicing

**Expected results**
Completes slicing

**Additional Information**
Log file shows error message
Trying to retrieve setting with no value given: 'bridge_extend_floating_walls'

No setting by that name is found when selecting settings visibility.
Could this have been from skipping version 20200304? That version has note regarding adding that seeting.

**Comment by smartavionics** [comment]
Hi, we've seen this kind of error before. I think a fix is to delete the cura cache directory. Try removing ~/Library/Application Support/cura/master/cache. Hope this helps!

**Comment by Funkton** [comment]
Yup that did the trick! Thank you for the quick reply. Love your dev builds BTW. Discovering them kept me from dumping Cura.
