### ISSUE TITLE
[master-20190407] Printer unable too keep up? (Stutter/Underextrusion)

### ISSUE THREAD

**Issue by Timocop** [smartavionics/CuraEngine#5]
**Platform**
Windows 10 64x

**Steps to Reproduce**
Is happens even at 30mm/s, 0.6mm nozzle, 0.3mm layer height. Its probably more noticable with 60mm/s. Cura 4.0 prints fine.
Watch as it prints inner curvy walls.

Ive seen it 'pull' ozzed material like gum while its stuttering. I doubt its intended.
Max resolution is at 0.01 (default).

**Actual Results**
Stuttering, Underextrusion

**Additional Information**
Video. May me not much noticable, but still audable, listen closely:
https://streamable.com/cohun
The inner front curvy walls of the benchy are thinner than normal making outer wall seams more visible:
![](https://user-images.githubusercontent.com/22834512/56002627-6e467480-5cc3-11e9-9be9-bfce6a7ffa2a.png)

**Comment by Timocop** [comment]
Printer is: Geeetech Prusa i3 Pro W (Marlin)

**Comment by smartavionics** [comment]
Hi @Timocop , please provide the project file. Thanks.

**Comment by Timocop** [comment]
Here you go
[PI3_#3DBenchy.zip](https://github.com/smartavionics/CuraEngine/files/3074206/PI3_.3DBenchy.zip)

**Comment by smartavionics** [comment]
There does appear to be many variations in line width on the hull. There have been upstream changes that have altered the simplification of polygons (they are simplified to reduce the number of points which makes slicing quicker). I think the old simplification code was rather too aggressive, the new code leaves more points but I wasn't involved in that work.  I can't think of any changes specific to my Cura that would cause the variation in extrusion rate seen here.

![Screenshot_2019-04-12_18-50-21](https://user-images.githubusercontent.com/585618/56056614-9c27c980-5d54-11e9-926c-d9282515d38c.png)

**Comment by Timocop** [comment]
I saw the pull request on the orginal Cura github before. Already assumed it was that. Your version seems to have it already compiled. :/

Whats the actual resolution of the output? Any way to fix it?

**Comment by Timocop** [comment]
Not sure if its related but after the fix Cura doesnt seem to care much about the maximum resolution now? The GCode output is twice as big than the older version. Let alone for the last piece of the benchy outer wall the gcode for it is 3x longer. I assume thats why my printer cant keep up printing it at 30mm/s.
![](https://i.imgur.com/UMBFbHk.png)

Last piece of benchy gcode (Res: 0.01):
https://pastebin.com/BKYzwx2V (Old Version, steady print speed in virtualizer)
https://pastebin.com/xPEk3MCm (New Version, random speed changes in virtualizer)

**Comment by smartavionics** [comment]
Using a max resolution of 1 cleans up that hull nicely (but, of course, makes everything else too coarse)

![Screenshot_2019-04-13_08-01-34](https://user-images.githubusercontent.com/585618/56075964-a7194300-5dc2-11e9-92c5-4eda6163dd51.png)

**Comment by Timocop** [comment]
Hello @smartavionics, this bug has been fixed and merged in the orginal branch (https://github.com/Ultimaker/Cura/pull/5620). Are you able to merge it to your branch? So im finaly able to test your commits you made. Thank you :)

**Comment by smartavionics** [comment]
Hello @Timocop , I will build a release soon. I think there is a small problem with that recent change in that the default value for the max travel resolution is now too big when the printer is capable of fast travel moves. I am waiting for a reply from the Cura devs.

**Comment by TheTiEr** [comment]
> Using a max resolution of 1 cleans up that hull nicely (but, of course, makes everything else too coarse)
> 
> ![Screenshot_2019-04-13_08-01-34](https://user-images.githubusercontent.com/585618/56075964-a7194300-5dc2-11e9-92c5-4eda6163dd51.png)

Hi @smartavionics, what software are you using to visualise the gcode files? It looks pretty decent to analyze the generated path.

Greetings

**Comment by smartavionics** [comment]
I use craftware (on Linux). It's a slicer also but I only use it as a gcode viewer. It has some glitches but is still useful.
