### ISSUE TITLE
[Cura-mb-master-win64-20190420] Cura Engine crashes if object is in the air and custom support is added

### ISSUE THREAD

**Issue by TheTiEr** [smartavionics/CuraEngine#6]
**Application Version**
Cura-mb-master-win64-20190420

**Platform**
Windows 10 

**Steps to Reproduce**
Add Custom support, move the model some mm into the air (disable *automatically drop models to the build plate* in preferences)

**Actual Results**
Cura Engine Crashes and no gcode will be generated

**Expected results**
no crash -> GCode file

**Additional Information**
CuraEngineBackend.CuraEngineBackend._onBackendQuit [808]: Backend quit with return code 3221225477. Resetting process and socket.

**Comment by smartavionics** [comment]
Thanks for the report. That bug has already been spotted and fixed by the eagle-eyed people at Ultimaker (very nice of them to find and fix my bugs as I was the culprit). The next release (later today) will be fixed. Sorry for the inconvenience.

**Comment by TheTiEr** [comment]
You are welcome. I highly appreciate your work. This software profits from your good work. 

Greetings

**Comment by smartavionics** [comment]
New build now available that (I believe) fixes this problem.
